[tool.black]
line-length = 120
target_version = ['py37', 'py38', 'py39', 'py310']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.tox
    | \.venv
    | build
    | dist
    | pip-wheel-metadata
    | examples
  )/
)
'''
