[tool.black]
line-length = 120
target_version = ['py27', 'py37', 'py36', 'py38']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.tox
    | \.venv
    | build
    | dist
    | pip-wheel-metadata
    | examples
  )/
)
'''
