Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ${codeuri}
      MemorySize: 128
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
          - https://foo.com
          AllowMethods:
          - POST
          AllowCredentials: true
          AllowHeaders:
          - x-Custom-Header
          ExposeHeaders:
          - x-amzn-header
          MaxAge: 10
Metadata:
  SamTransformTest: true
