Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ${codeuri}
      MemorySize: 128
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Policies:
      - AWSLambdaRole
      - AmazonS3ReadOnlyAccess
Metadata:
  SamTransformTest: true
